### ISSUE TITLE
error in data.py: name 'get_filenames' is not defined.

### ISSUE THREAD

**Issue by linzi-h** [sklcg/shlight#5]
Traceback (most recent call last):
  File "predict.py", line 57, in <module>
    for pred in predictions:
  File "C:\Users\linhui\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\estimator\estimator.py", line 549, in predict
    input_fn, model_fn_lib.ModeKeys.PREDICT)
  File "C:\Users\linhui\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\estimator\estimator.py", line 1024, in _get_features_from_input_fn
    result = self._call_input_fn(input_fn, mode)
  File "C:\Users\linhui\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\estimator\estimator.py", line 1136, in _call_input_fn
    return input_fn(**kwargs)
  File "D:\experiment\shlight\src\data.py", line 90, in pred_input
    data = tf.data.TextLineDataset(os.path.join(data_root,'pred.txt')).map(get_filenames).map(_load_data)
NameError: name 'get_filenames' is not defined

**Comment by sklcg** [comment]
Thank you very much for your patience.
The latest version of the code has been uploaded.  This version of the code has been tested many times to make sure it works correctly. Since predict.py in previous versions of the code may be incorrect, we strongly recommend that you **use all the code of the current version.**
